import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/layout/theme/theme-provider';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/layout/nav/app-sidebar';
import { ActiveNavItem } from '@/components/layout/nav/active';
import { Toaster } from '@/components/ui/toaster';
const inter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(inter.variable, 'antialiased')} suppressHydrationWarning>
      <body className={cn(inter.variable, 'antialiased')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="erp-theme"
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="flex flex-1 flex-col">
              <header className="flex sticky top-0 shrink-0 items-center gap-2 z-50">
                <div className="flex w-full items-center h-16 bg-background/80 backdrop-blur-sm px-3 mt-0">
                  <SidebarTrigger />
                  <ActiveNavItem />
                </div>
              </header>
              <div className="flex flex-1 flex-col p-4 pt-0">{children}</div>
            </main>
            <Toaster />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
